/*
 * Copyright (c) 2014, Bruce Schubert <bruce@emxsys.com>
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * - Redistributions of source code must retain the above copyright notice, 
 *   this list of conditions and the following disclaimer.
 * 
 * - Redistributions in binary form must reproduce the above copyright notice, 
 *   this list of conditions and the following disclaimer in the documentation 
 *   and/or other materials provided with the distribution.
 * 
 * - Neither the name of Bruce Schubert, Emxsys nor the names of its contributors 
 *   may be used to endorse or promote products derived from this software 
 *   without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR 
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.terramenta.ribbon.options;

import com.terramenta.ribbon.spi.RibbonPreferencesProvider;
import java.util.prefs.Preferences;
import org.openide.util.Lookup;
import org.openide.util.NbPreferences;

final class RibbonOptionsPanel extends javax.swing.JPanel {

    private static final Preferences prefs = NbPreferences.forModule(RibbonOptions.class);
    private final RibbonOptionsPanelController controller;
    private String currentStyle;

    RibbonOptionsPanel(RibbonOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        styleButtonGroup = new javax.swing.ButtonGroup();
        stylePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        style1RadioButton = new javax.swing.JRadioButton();
        style1Label = new javax.swing.JLabel();
        style2RadioButton = new javax.swing.JRadioButton();
        style2Label = new javax.swing.JLabel();
        style3Label = new javax.swing.JLabel();
        style3RadioButton = new javax.swing.JRadioButton();
        style4Label = new javax.swing.JLabel();
        style4RadioButton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        otherRadioButton = new javax.swing.JRadioButton();
        otherLabel = new javax.swing.JLabel();

        stylePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.stylePanel.border.title_1"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.jPanel1.border.title"))); // NOI18N

        styleButtonGroup.add(style1RadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(style1RadioButton, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.style1RadioButton.text")); // NOI18N

        style1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/terramenta/ribbon/images/office2013-fullsize-example.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(style1Label, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.style1Label.text")); // NOI18N
        style1Label.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        style1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                style1LabelMouseClicked(evt);
            }
        });

        styleButtonGroup.add(style2RadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(style2RadioButton, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.style2RadioButton.text")); // NOI18N

        style2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/terramenta/ribbon/images/office2007-full.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(style2Label, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.style2Label.text")); // NOI18N
        style2Label.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        style2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                style2LabelMouseClicked(evt);
            }
        });

        style3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/terramenta/ribbon/images/office2013-compact-example.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(style3Label, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.style3Label.text")); // NOI18N
        style3Label.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        style3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                style3LabelMouseClicked(evt);
            }
        });

        styleButtonGroup.add(style3RadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(style3RadioButton, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.style3RadioButton.text")); // NOI18N

        style4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/terramenta/ribbon/images/office2007-compact.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(style4Label, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.style4Label.text")); // NOI18N
        style4Label.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        style4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                style4LabelMouseClicked(evt);
            }
        });

        styleButtonGroup.add(style4RadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(style4RadioButton, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.style4RadioButton.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(style1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(style1RadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(style2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(style2RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(style3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(style3RadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(style4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(style4RadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(style2RadioButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(style1RadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(style1Label)
                            .addComponent(style2Label)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(style3RadioButton)
                            .addComponent(style4RadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(style3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(style4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.jPanel3.border.title"))); // NOI18N

        styleButtonGroup.add(otherRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(otherRadioButton, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.otherRadioButton.text")); // NOI18N

        otherLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(otherLabel, org.openide.util.NbBundle.getMessage(RibbonOptionsPanel.class, "RibbonOptionsPanel.otherLabel.text")); // NOI18N
        otherLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                otherLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(otherRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otherLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout stylePanelLayout = new javax.swing.GroupLayout(stylePanel);
        stylePanel.setLayout(stylePanelLayout);
        stylePanelLayout.setHorizontalGroup(
            stylePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stylePanelLayout.createSequentialGroup()
                .addGroup(stylePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        stylePanelLayout.setVerticalGroup(
            stylePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stylePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stylePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stylePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void style1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_style1LabelMouseClicked
        // Select 
        style1RadioButton.setSelected(true);
    }//GEN-LAST:event_style1LabelMouseClicked

    private void style3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_style3LabelMouseClicked
        // Select
        style3RadioButton.setSelected(true);
    }//GEN-LAST:event_style3LabelMouseClicked

    private void otherLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_otherLabelMouseClicked
        // TODO add your handling code here:
        if (otherRadioButton.isEnabled()) {
            otherRadioButton.setSelected(true);
        }
    }//GEN-LAST:event_otherLabelMouseClicked

    private void style2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_style2LabelMouseClicked
        style2RadioButton.setSelected(true);
    }//GEN-LAST:event_style2LabelMouseClicked

    private void style4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_style4LabelMouseClicked
        style4RadioButton.setSelected(true);
    }//GEN-LAST:event_style4LabelMouseClicked

    void load() {

        // Enable "Other" option if a 3rd party is providing the Ribbon UI
        RibbonPreferencesProvider provider = Lookup.getDefault().lookup(RibbonPreferencesProvider.class);
        otherRadioButton.setEnabled(provider != null);
        otherLabel.setText(provider != null ? provider.getPreferences().getClass().getSimpleName() : "");
        currentStyle = prefs.get(RibbonOptions.STYLE, RibbonOptions.DEFAULT_STYLE);
        switch (currentStyle) {
            case RibbonOptions.OFFICE2013_FULLSIZE_STYLE:
                style1RadioButton.setSelected(true);
                break;
            case RibbonOptions.OFFICE2007_FULLSIZE_STYLE:
                style2RadioButton.setSelected(true);
                break;
            case RibbonOptions.OFFICE2013_COMPACT_STYLE:
                style3RadioButton.setSelected(true);
                break;
            case RibbonOptions.OFFICE2007_COMPACT_STYLE:
                style4RadioButton.setSelected(true);
                break;
            case RibbonOptions.OTHER_STYLE:
                otherRadioButton.setSelected(true);
                break;
            default:
                style3RadioButton.setSelected(true);
        }
    }

    void store() {
        String newStyle;
        if (style1RadioButton.isSelected()) {
            newStyle = RibbonOptions.OFFICE2013_FULLSIZE_STYLE;
        } else if (style2RadioButton.isSelected()) {
            newStyle = RibbonOptions.OFFICE2007_FULLSIZE_STYLE;
        } else if (style3RadioButton.isSelected()) {
            newStyle = RibbonOptions.OFFICE2013_COMPACT_STYLE;
        } else if (style4RadioButton.isSelected()) {
            newStyle = RibbonOptions.OFFICE2007_COMPACT_STYLE;
        } else {
            newStyle = RibbonOptions.OTHER_STYLE;
        }
        prefs.put(RibbonOptions.STYLE, newStyle);
        if (!(currentStyle.equals(newStyle)))
        {
            controller.changed();
        }
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel otherLabel;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JLabel style1Label;
    private javax.swing.JRadioButton style1RadioButton;
    private javax.swing.JLabel style2Label;
    private javax.swing.JRadioButton style2RadioButton;
    private javax.swing.JLabel style3Label;
    private javax.swing.JRadioButton style3RadioButton;
    private javax.swing.JLabel style4Label;
    private javax.swing.JRadioButton style4RadioButton;
    private javax.swing.ButtonGroup styleButtonGroup;
    private javax.swing.JPanel stylePanel;
    // End of variables declaration//GEN-END:variables
}
