/**
 * Copyright © 2014, Terramenta. All rights reserved.
 *
 * This work is subject to the terms of either
 * the GNU General Public License Version 3 ("GPL") or
 * the Common Development and Distribution License("CDDL") (collectively, the "License").
 * You may not use this work except in compliance with the License.
 *
 * You can obtain a copy of the License at
 * http://opensource.org/licenses/CDDL-1.0
 * http://opensource.org/licenses/GPL-3.0
 */
package com.terramenta.time.timeline;

import com.terramenta.ribbon.RibbonActionReference;
import com.terramenta.time.DatetimeProvider;
import com.terramenta.time.actions.TimeActionController;
import java.time.Duration;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import org.openide.awt.ActionID;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@TopComponent.Description(
        preferredID = "TimelineTopComponent",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "bottomSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "com.terramenta.time.timeline.TimelineTopComponent")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
@RibbonActionReference(
        path = "Menu/Animate/Controls",
        position = 6
)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TimelineAction",
        preferredID = "TimelineTopComponent"
)
@Messages({
    "CTL_TimelineAction=Timeline",
    "CTL_TimelineTopComponent=Timeline Window",
    "HINT_TimelineTopComponent=This is the Timeline window"
})
public final class TimelineTopComponent extends TopComponent {

    private static final DatetimeProvider dtp = Lookup.getDefault().lookup(DatetimeProvider.class);
    private static final TimeActionController tac = Lookup.getDefault().lookup(TimeActionController.class);

    private final Timeline timeline;
    public TimelineTopComponent() {
        initComponents();
        setName(Bundle.CTL_TimelineTopComponent());
        setToolTipText(Bundle.HINT_TimelineTopComponent());
        //putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);

        Duration displayDuration = tac.getDisplayDuration();
        Duration timelineDuration = displayDuration.isZero() ? Duration.ofDays(1) : displayDuration.multipliedBy(3);
        timeline = new Timeline(dtp.getDatetime(), displayDuration, timelineDuration);
        //listen for date changes
        dtp.addChangeListener((oldDatetime, newDatetime) -> {
            timeline.setDisplayDatetime(newDatetime);
        });

        //update Timeline to reflect changes in display duration
        tac.addPropertyChangeListener(pce -> {
            if (pce.getPropertyName().equals(TimeActionController.DURATION)) {
                timeline.setDisplayDuration((Duration) pce.getNewValue());
            }
        });

        //update DatetimeProvider to reflect changes in display date
        timeline.displayDateProperty().addListener((obs, oldDatetime, newDatetime) -> {
            dtp.setDatetime(newDatetime);
        });
        
        //update TimeActionController to reflect changes in display duration
        timeline.displayDurationProperty().addListener((obs, oldDuration, newDuration) -> {
            tac.setDisplayDuration(newDuration);
        });
        //TimelinePlot timeline = new TimelinePlot();
        Platform.runLater(() -> {
            //timeline.setControlsEnabled(true);
            jFXPanel1.setScene(new Scene(new StackPane(timeline), Color.DARKGRAY));
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFXPanel1 = new javafx.embed.swing.JFXPanel();

        setLayout(new java.awt.BorderLayout());
        add(jFXPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javafx.embed.swing.JFXPanel jFXPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {

    }

    @Override
    public void componentClosed() {

    }
}
