/*
 * To change this template, choose Tools | Templates and open the template in the editor.
 */

/*
 * LayerSelectorPanel.java
 *
 * Created on Jan 10, 2011, 2:03:28 PM
 */
package com.terramenta.layermanager;

import com.terramenta.globe.layers.KMLLayer;
import gov.nasa.worldwind.layers.Layer;
import gov.nasa.worldwind.layers.SurfaceImageLayer;
import gov.nasa.worldwindx.examples.util.ShapefileLoader;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.openide.util.Exceptions;

/**
 *
 * @author heidtmare
 */
public class LayerSelectorPanel extends javax.swing.JPanel {

    private final static Logger LOGGER = Logger.getLogger(LayerSelectorPanel.class.getName());
    private final JFileChooser fileChooser = new JFileChooser();

    /** Creates new form LayerSelectorPanel */
    public LayerSelectorPanel() {
        initComponents();
    }

    /**
     * 
     * @return
     */
    public Layer getLayer() {
        String type = (String) jComboBox1.getSelectedItem();
        String text = jTextField1.getText();
        if (!text.isEmpty()) {
            try {
                if (type.equals("KML")) {
                    LOGGER.log(Level.INFO, "Adding a KML layer for {0}", text);
                    return new KMLLayer(text);
                } else if (type.equals("Shapefile")) {
                    LOGGER.log(Level.INFO, "Adding a Shapefile layer for {0}", text);
                    ShapefileLoader loader = new ShapefileLoader();
                    return (Layer) loader.createLayersFromSource(new URL(text));
                } else if (type.equals("GeoTiff")) {
                    LOGGER.log(Level.INFO, "Adding a GeoTiff layer for {0}", text);
                    SurfaceImageLayer sil = new SurfaceImageLayer();
                    sil.addImage(text);
                    return sil;
                }
            } catch (IOException ex) {
                Exceptions.printStackTrace(ex);
            }
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(LayerSelectorPanel.class, "LayerSelectorPanel.jLabel1.text_1")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GeoTiff", "KML", "Shapefile" }));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(LayerSelectorPanel.class, "LayerSelectorPanel.jLabel2.text_1")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(LayerSelectorPanel.class, "LayerSelectorPanel.jTextField1.text_1")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(LayerSelectorPanel.class, "LayerSelectorPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 180, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("KML/KMZ File", "kml", "kmz"));
        int status = fileChooser.showOpenDialog(this);
        if (status == JFileChooser.APPROVE_OPTION) {
            try {
                jTextField1.setText(fileChooser.getSelectedFile().toURI().toURL().toString());
            } catch (MalformedURLException ex) {
                Exceptions.printStackTrace(ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
