/*
 * To change this template, choose Tools | Templates and open the template in the editor.
 */
package com.terramenta.layermanager.layerselector;

import javax.swing.JPanel;

public final class LayerSelectorLayerTypeView extends JPanel {

    /**
     * Creates new form LayerSelectorLayerTypeView
     */
    public LayerSelectorLayerTypeView() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Select Layer Type";
    }

    public String getLayerType() {
        return this.buttonGroup1.getSelection().getActionCommand();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(LayerSelectorLayerTypeView.class, "LayerSelectorLayerTypeView.jLabel1.text_2")); // NOI18N
        add(jLabel1);

        buttonGroup1.add(jRadioButton1);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton1, org.openide.util.NbBundle.getMessage(LayerSelectorLayerTypeView.class, "LayerSelectorLayerTypeView.jRadioButton1.text_2")); // NOI18N
        jRadioButton1.setActionCommand(org.openide.util.NbBundle.getMessage(LayerSelectorLayerTypeView.class, "LayerSelectorLayerTypeView.jRadioButton1.actionCommand")); // NOI18N
        add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton2, org.openide.util.NbBundle.getMessage(LayerSelectorLayerTypeView.class, "LayerSelectorLayerTypeView.jRadioButton2.text_2")); // NOI18N
        jRadioButton2.setActionCommand(org.openide.util.NbBundle.getMessage(LayerSelectorLayerTypeView.class, "LayerSelectorLayerTypeView.jRadioButton2.actionCommand")); // NOI18N
        add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton3, org.openide.util.NbBundle.getMessage(LayerSelectorLayerTypeView.class, "LayerSelectorLayerTypeView.jRadioButton3.text_2")); // NOI18N
        jRadioButton3.setActionCommand(org.openide.util.NbBundle.getMessage(LayerSelectorLayerTypeView.class, "LayerSelectorLayerTypeView.jRadioButton3.actionCommand")); // NOI18N
        add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton4, org.openide.util.NbBundle.getMessage(LayerSelectorLayerTypeView.class, "LayerSelectorLayerTypeView.jRadioButton4.text_2")); // NOI18N
        jRadioButton4.setActionCommand(org.openide.util.NbBundle.getMessage(LayerSelectorLayerTypeView.class, "LayerSelectorLayerTypeView.jRadioButton4.actionCommand")); // NOI18N
        add(jRadioButton4);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
